const chapters = {
  Chemistry: {
    eleventh: [
      "Some Basic Concepts of Chemistry",
      "Structure of Atom",
      "Classification of Elements and Periodicity in Properties",
      "Chemical Bonding and Molecular Structure",
      "States of Matter",
      "Thermodynamics (Chemistry)",
      "Equilibrium",
      "Redox Reactions",
      "Hydrogen",
      "The s-Block Elements",
      "The p-Block Elements (Group 13,14)",
      "Organic Chemistry – Some Basic Principles & Techniques",
      "Hydrocarbons",
      "Environmental Chemistry",
    ],
    twelveth: [
      "The Solid State",
      "Solutions",
      "Electrochemistry",
      "Chemical Kinetics",
      "Surface Chemistry",
      "Metallurgy",
      "The p-Block Elements (Group 15-18)",
      "The d & f Block Elements",
      "Coordination Compounds",
      "Haloalkanes and Haloarenes",
      "Alcohols, Phenols, and Ethers",
      "Aldehydes, Ketones, and Carboxylic Acids",
      "Amines",
      "Biomolecules",
      "Polymers",
      "Chemistry in Everyday Life",
    ],
  },
  Physics: {
    eleventh: [
      "Units and Measurements",
      "Motion in a Straight Line",
      "Motion in a Plane",
      "Laws of Motion",
      "Work, Energy, and Power",
      "Systems of Particles and Rotational Motion",
      "Gravitation",
      "Mechanical Properties of Solids",
      "Mechanical Properties of Fluids",
      "Thermal Properties of Matter",
      "Thermodynamics (Physics)",
      "Kinetic Theory of Gas",
      "Oscillations",
      "Waves",
    ],
    twelveth: [
      "Electrostatics",
      "Capacitance",
      "Current Electricity",
      "Moving Charges and Magnetism",
      "Magnetism and Matter",
      "Electromagnetic Induction",
      "Alternating Current",
      "Electromagnetic Waves",
      "Ray Optics and Optical Instruments",
      "Wave Optics",
      "Dual Nature of Radiation and Matter",
      "Atoms",
      "Nuclei",
      "Semiconductor Electronics",
      "Communication Systems",
    ],
  },
  Mathematics: {
    eleventh: [
      "Sets",
      "Relations",
      "Functions",
      "Trigonometric Functions/Equations",
      "Complex Numbers",
      "Quadratic Equations",
      "Permutations and Combinations",
      "Binomial Theorem",
      "Sequences and Series",
      "Straight lines",
      "Circles",
      "Parabola",
      "Ellipse",
      "Hyperbola",
      "Limits and Derivatives",
      "Mathematical Reasoning",
      "Statistics",
    ],
    twelveth: [
      "Relations and Functions",
      "Inverse Trigonometric Functions",
      "Matrices",
      "Determinants",
      "Continuity and Differentiability",
      "Applications of Derivatives",
      "Integrals",
      "Applications of Integrals",
      "Differential Equations",
      "Vector Algebra",
      "Three dimensional Geometry",
      "Probability",
    ],
  },
};

export default chapters;
